### ISSUE TITLE
Publish as crate

### ISSUE THREAD

**Issue by virtumonde** [georust/geotiff#2]
Hi @dominikbucher. Can you add this as a crate on crates.io?

**Comment by virtumonde** [comment]
I published it myself.  Please post a message when you would like to get the ownership over the crate.

**Comment by dominikbucher** [comment]
👍🏻 Just note that "in its current state, it works for very basic GeoTIFFs, which sufficed to extract elevation data for use in the routing library". It's by far not implementing the whole GeoTIFF spec and thus might not suffice, depending on the use case.
